<?php

namespace Usuario\Bundle\UsuarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 *  pessoasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class  pessoasRepository extends EntityRepository
{
}
