<?php

namespace Usuario\Bundle\UsuarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 *  PessoasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class  PessoasRepository extends EntityRepository
{
}
